### ISSUE TITLE
Commands not registered in 5.8

### ISSUE THREAD

**Issue by Braunson** [Niellles/lumen-commands#5]
Commands not registered in 5.8 it seems, it's registered in the AppServiceProvider register method but doesn't appear in artisan..

**Comment by Braunson** [comment]
Nevermind figured it out. Enabled the register of AppServiceProvider in `bootstrap/app.php`

Then in the `AppServiceProvider.php` `register` method I added..

```
        if (env('APP_ENV') === 'local') {
            $this->app->bind(Illuminate\Database\ConnectionResolverInterface::class, Illuminate\Database\ConnectionResolver::class);
            $this->app->register(\Niellles\LumenCommands\LumenCommandsServiceProvider::class);
        }
```

And it works now.. I guess I feel registering it in bootstrap is messy..

**Comment by Niellles** [comment]
I'm just seeing this issue now. You've essentially added the code that's required to make this work, just in another place than described in the README.

It's been a while since I did anything with Lumen and/or Laravel, but if I remember correctly there's multiple ways to register service providers. Looking at the the code that's added to `app.php` for this package, I doubt whether the way I am currently doing it is the most elegant. I'll look into it when I get the time.

P.s. I am glad you got it working.
