### ISSUE TITLE
Compatibility issue with the 6.x version

### ISSUE THREAD

**Issue by simaremare** [Niellles/lumen-commands#7]
I tried the package in a Lumen 6.x project. it is not compatible.

**Comment by Niellles** [comment]
Thanks for letting me know. I've not used Lumen in a while, also I've not yet tried Lumen 6.0.

Could you give me some more pointers as to what's not working? Are you getting errors during install? Or will it install just fine, but then not do anything as you try to use the package?

----
This package was originally developed for Lumen 5.*. Since I'm not currently developing anything with Lumen I am not too inclined to make it work with Lumens new release. However, if you could provide me with some more information about the issue (and it turns out to be a rather simple fix) I'll be happy to make this work again.

Right now I am really hoping that it's just this entry in `composer.json` that's causing issues:
 ```
"require": {
    "laravel/lumen-framework": "5.*.*"
  },
```

**Comment by Niellles** [comment]
This issue should be fixed later this weekend.

**Comment by Niellles** [comment]
[Pull request merged](https://github.com/Niellles/lumen-commands/pull/8).
This issue should now be resolved.
